== There's too much content to maintain

Talk to any documentation team and I guarantee they'll say they're behind, buried in work, barely holding on, or have little to no time for new initiatives.
While this has always been true to a certain degree, the situation has worsened.
The reasons is that the nature of software development has changed.
Both the pace of development has increased and the surface area of what needs to be documented (particularly REST APIs) has expanded drastically.
Unless we change how writers work, a finite (often too small) team of writers just isn't going to scale.
(slide concept: "work smater, not harder graphic"; maybe even "pause. think. ...")
They need to work smarter, not harder.
That means finding ways to get them out of doing rote tasks and focus their efforts on writing instead.

Let's consider some engineering practices that reduce their workload.

//What's one of the main techniques we use in development to reduce the surface area of what we have to maintain?
//(interaction)
//Look, we're already violating the rule. DRY: Don't Repeat Yourself.

I knew of one documentation team that was spending a substantial amount of time updating version numbers whenever a new version was released or a product was renamed.
And let's be honestly, both of those are equally likely.
How do we avoid having to change the same information in multiple places?
Variables, of course.
Writers could use variables (which in AsciiDoc we call attributes) as placeholders instead of hardcoding version numbers and product names.
(slide concept: example)
Not only does this save writers time, it also reduces the chance of the reader seeing the wrong product name or version number.
You can probably think of other examples where this practice can be used.

Variables are good for short strings, but what about whole paragraphs or sections?
Does it make sense to have to update a product description, reference table, or common set of instructions in multiple places?
Of course not.
This information should be centralized.
We can move this content into a document fragment, then simply include it whereever it's needed.
(slide concept: example)
That document fragment could even been generated by a tool, such as Spring RESTDocs, which totally gets the writer off the hook of having to update it at all.

To save even more of the writer's time, you could combine the last two techniques by including shared fragments that themselves have placeholders that are populated from attributes.
The Spring team does this for the common parts of their quickstart guides.
(slide concept: example)

(slide concept: D路R路Y)
These last two practices are grouped under the heading of DRY: or Don't Repeat Yourself.
The goal is to avoid having to do exactly the same thing twice.
If the writer's time is finite and ever more scarce, we want that writer focusing on original tasks, not repeat ones.

Another problem I see is writers creating documents that could have been generated.
A great example of this are release notes.
I knew a documentation team that was creating release notes files for every release of every product, for which there were many.
Why would a writer be recreating release notes files when all that information is available elsewhere, such as in the issue tracker or VCS log.
It would kind of be like writing the JavaDoc manually.
Running the air conditioner with the windows open wouldn't be as inefficient.
The writer is not really adding anything, and may even be making omissions.
But it sure is a time suck.
Surely these files can be generated and published somewhere by the software release process.
Better yet, the release process could generate documentation artifacts in a format the documentation tool can consume, such as HTML, AsciiDoc, or JSON.
Show them that they never have to create release notes again because you've automated them.
Automatically generate these reports and have them enlisted in the documentation workflow.

Another example is reference documentation such as the documentation for a REST API.
There's no way a small group of writers can document hundreds of API calls and keep that documentation in sync with the constantly evolving code.
Doing it manually is tedious, boring, and prone to error.
We need to work smarter.
You should use a tool like Spring RESTDocs to generate documentation directly from the code.
The documentation writers can then include this reference information into their documentation and focus on writing the copy to introduce it and provide context and use cases.
They can focus on the story around it because they've recaptured the time they were losing itemizing all the methods and parameters.

You should look for a similar type of solution for creating other types of reference documentation, such as a table of configuration properties or environment variables.
Software developers should be mindful of giving the documentation team a lot of work that could be offloaded to a tool.

(slide concept: N路D路I)
The message to communicate to writers is this:
Why write what the computer can generate for you?
This goes even further than DRY.
It's NDI.
Never Do It.

The nature of software development has changed, and so must the documentation tools.
If the docs team expects to keep up with software development, they too must adopt these DRY and NDI practices.
