= Poor Editing Workflow
////
SAW: I'm going to need to work on this one in layers, it's too "surface layer" at the moment to really feel like it is providing value.
But I'm pretty sure I know how to fix it and make it realize its full potential.
////

////
If you link to a wiki page or Google docs, can we just acknowledge that means that your documentation workflow is problematic.
////

Imagine you're sitting at your desk hacking away on some code when you receive an e-mail from another programmer.

// Problem; Screenshot
Slide: Screenshot of the hypothetical email described below; or e-mail with attachment icon

The subject line reads, "`for your review`".
The text explains, "`I edited this source file to implement feature A and fix bug B. Can you merge it?`"
Attached to the e-mail is a Java source file.

Let me ask.
What would be your reaction?

Just as I suspected.
You're horrified.
(slide concept: 😱)

If this behavior is a no-no for development, why on earth do we let it happen for documentation?

You immediately head over to your colleague's desk.
What are you going to say?
Well, you'd probably say, "`please submit this change as a pull request`".

It doesn't matter if we're talking about writing or coding.
Pull requests instead of e-mail.

I want to read an excerpt from the Docs Like Code book that explains how the book was written.

> Kelly first edited the chapters individually by creating Word documents from the Markdown files, marking them up, and creating PDFs from them to make the tracked changes easier to read.
Then, she created issues for each chapter's edits, and Diane and Anne made pull requests with the suggested edits.
As a final quality check, Kelly edited the book as a whole, creating pull requests with final copy edits.

It's getting there.
Pull requests, good.
Pulling the Markdown files out of the process and into Word, then producing a read-only PDF.
Not so much.

The key to working collaboratively is keeping the content in the system and storing it as plain text.
A text-only format can be diffed, so there's no need for track changes.
The version control system gives you that for free.
You can make your changes, then submit a pull request so those changes can be reviewed and merged by another writer, just like with the code.

// DJA: we might want to move this point under code review process
Both GitHub and GitLab even have a feature that allows authors edit the files directly through the web interface and submit a pull request on save.
This is a great way to warm up authors to this new workflow.
Versioning is automatic, and the web interface gives you an integrated discussion thread to discuss the changes.
And what does that lead us to?

Who said "`a code review process`"?
You got it!
Who needs track changes when you have a full code review system at your finger tips?
Authors can look a what lines changed, even previewing those changes with a "rich diff", they can comment on a change to seek clarification or request an update, they can approve or decline a set of changes, and they can merge the changes into master or another branch (even applying it multiple times).
The point is, a code review tool is just as powerful for writing as it is for coding.
And writers should be leveraging it.

This is all sounding good, but there's one small problem.
git.
Writers have to learn git.
And that can be...tricky.

// Problem example; screenshot
Slide: I hate git tweet screenshot

If only they worked with people who know git amazingly well and can teach them.
Oh, wait.
That's you.
Writers really only need to know a few key concepts and commands to be successful.
clone, fetch, pull, rebase, branch, status, commit (and how to write a good commit message).
branch is super important.
rebase is a nice stretch goal, but don't scare them away with it.
// SAW: I'm worried that this feels like a throw-away point. The cynic in me says who's going to take the time to teach anyone git if teaching git isn't their job. Followed by, oh please, god no, don't let developers teach writers all their terrible git habits
So please, if there's nothing else you take away from this talk, please go back and teach your writers how to be dangerous with git.

Before we wrap up this topic, there's one more thing to address.
Where do these magical changes to the documentation come from?
Do code changes just come out of the blue?
Of course not.
They stem from issues.
Again, why shouldn't documentation follow the same process?
If a change is needed to the documentation, or a new documentation page needs to be written, it should originate with an issue.
That issue explains the motivation for the change, the acceptance criteria, and anything else that needs to be discussed.
It's a system for tracking the work to be performed, the initiatives.
It can be used to communicate when those changes are due...which implies the use of milestones, roadmap or issue board.
It does make you wonder how to define milestones for documentation.
What's a documentation release?

Just as issues help shine light on development, issues for documentation shine light on the writing process so it's not such a black box.
If the writers are using an issue tracker, and you file a well explained documentation request, maybe the result will be that you will have helped birth some new documentation.
For once, you aren't the one being asked to implement something.
A nice feeling, isn't it?

If the documentation has an established contribution workflow based on the tools I just mentioned, then the team could enforce that all changes have to go through process.
No offline editing.
No emails.
No binary blobs for content.
No proprietary, black box editing tools.
We know that works for development, so it's reasonable to assume that will have a real positive impact on development.
And please, teach them git.
