// ci server carosel
= Publishing is Painful

Once you make a change, you know people are going to ask when it will published.
Heck, you want it published too.
But right now, this is an extremely painful process for writers.
You see, the writing part is easy for them.
It's what they do.
But then there's this huge barrier they need to scale in order to get their words to a place where people can read them.
They find themselves quickly in over their heads because it's not a wall they know how to free climb.

It shouldn't be.
Every step between making a change and publishing should be completely automated.
In engineering, we recognize this as the practice of continuous delivery.
In writing, like to call it "`push to publish`".
Then, all writers really do have to do is write.

There's a lot more to gain from continuous delivery, push to publish, than just speed and producitivity.
A CD process completely eradicates manual steps.
And trust me, this is a place where manual steps love to fester.
We worked with one client who required a person to manually run the build, then manually copy all the files to a CMS using a web interface, then manual press the publish button.
That's ludicrous.

What you want is to be able to describe the entire publishing process in a script so you can run it exactly the same every time any time you want.
That implies that the documentation has a build, but even more than that.
It means that all the configuration for the documentation site is stored with the build, the practice of configuration as code.
The immediate benefit of a build is that it's makes the process self-documenting.
You don't have the find the person with the specialized knowledge about how the documentation site is generated.
It should all be right there in the build.

So the build is a prerequisite for achieving push to publish.
It also prevents drift between different environments.
We worked with another client who had a build, but the script lived exclusively in each CI job configuration.
That means no two CI jobs worked exactly the same way and there was no transparency.
I know, the horror.
I honestly feel sorry for the person who had to maintain them, except I really don't.
And let me just tell you, a script that only lives in Jenkins is not a script that is tested.
That story doesn't end well.

Some teams may buy into this automation process, but be weary of the delivery part.
Of course, you can add a gateway criteria for controlled releases.
But the point is, that step should be as simple as pressing a button.
As soon as a step is introduced that only one person knows how to perform, or it's documented in a wiki page somewhere, you're free climbing again.

We've talked about the publish part, but what about the push part.
What triggers this process.
That's another important aspect of CD.
There should be a process that watches for changes.
When a change is detected, perhaps on a qualified branch like the master branch or an active version branch, it should trigger the CD pipeline.
The secret here are webhooks.
A webhook essentially allows another application to subscribe to events that occur on GitHub.
For example, you can have a webhook fire when code is pushed to the repository.
The webhook will then send a ping to that application to let it know something interesting happened.
The receiver of that webhook can be the CI server, which can target and trigger a specific job.

The bottom line is, if you want to improve the documentation process, the best thing you can do is set up CD, or push to publish.
Publishing should never be manual.
It's very hard on the writer and it leads to inconsistencies.
With push to publish in place, the writer can just walk right across the border between development and production.
No barrier.

Once the production pipeline is set up with push to publish, the next logical step is automation for staging environments and the local environment.
