== There's too much content to maintain
////
SAW: I'm a bit concerned about the tone of this transcript, especially in the release notes section.
It sounds to me like the developers are being encouraged to chastise the docs team for not knowing about and/or how to set up automated release note generation.
Instead focus on getting developers to set this up and finding a solution (Antora!) to feed them into the docs team's pipeline.
////

Talk to any documentation team and I guarantee they'll say they're buried in work, barely holding on, or have no time for new initiatives.
While this has always been true to a certain degree, the situation has gotten worse.
The reason is that the nature of software development has changed.
Both the pace of development has increased and the surface area of what needs to be documented--particularly REST APIs--has expanded dramatically.
Unless we change how writers work, a finite (often too small) team of writers just isn't going to scale.
(slide concept: "work smarter, not harder graphic"; maybe even "pause. think. ...")
// SAW: smarter, not harder is much more specific to this situation than pause. think
They need to work smarter, not harder.
That means finding ways to get them out of doing rote tasks so they can focus their efforts on writing instead.

Let's consider some engineering practices that would reduce their workload.

//What's one of the main techniques we use in development to reduce the surface area of what we have to maintain?
//(interaction)
//Look, we're already violating the rule. DRY: Don't Repeat Yourself.

I knew of one documentation team that was spending a substantial amount of time manually searching and replacing version numbers every time a new version was released.
They had over 10 products.
Each product got released multiple times a year.
One or more of their products would also be renamed in a year.
That's a lot of search and replace.

How do we avoid having to change the same information in hundreds of places?
Variables, of course.
Writers could use variables--which in AsciiDoc we call attributes--as placeholders instead of hardcoding version numbers and product names.
(slide concept: example)
Not only does this save writers time, it also reduces the chance of the reader seeing the wrong product name or version number.
You can probably think of other examples where this practice can be used.

Variables are good for short strings, but what about whole paragraphs or sections?
Does it make sense to update a product description, reference table, or common set of instructions in multiple places?
Of course not.
This information should be centralized.
We can move this content into a document fragment, then simply include it where ever it's needed.
(slide concept: example)
That document fragment could even be generated by a tool, such as Spring RESTDocs, which totally gets the writer off the hook of having to update it at all.

To save even more of the writer's time, you could combine the last two techniques by including shared fragments that themselves have placeholders that are populated from attributes.
The Spring team does this for the common parts of their quickstart guides.
// SAW: Verify that the Spring team is still operating this way.
(slide concept: example)

(slide concept: D·R·Y)
These last two practices are classified as DRY: or Don't Repeat Yourself.
The goal is to avoid having to do exactly the same thing twice.
If the writer's time is finite and ever more scarce, we want that writer focusing on original tasks, not repeat ones.

Another problem I see is writers creating documents that could have been generated.
A great example of this are release notes.
I knew a documentation team that was creating release notes files for every release of every product, for which there were many.
Why would a writer be recreating release notes files when all that information is available elsewhere, such as in the issue tracker or VCS log.
It would kind of be like writing the JavaDoc manually.
Running the air conditioner with the windows open wouldn't be as inefficient.
The writer is not really adding anything, and may even be making omissions.
But it sure is a time suck.
Surely these files can be generated and published somewhere by the software release process.
Better yet, the release process could generate documentation artifacts in a format the documentation tool can consume, such as HTML, AsciiDoc, or JSON.
Show them that they never have to create release notes again because you've automated them.
Automatically generate these reports and have them enlisted in the documentation workflow.

// SAW: Are you going to use the OpenStack example here?
Another example is reference documentation such as the documentation for a REST API.
There's no way a small group of writers can document hundreds of API calls and keep that documentation in sync with the constantly evolving code.
Doing it manually is tedious, boring, and prone to error.
We need to work smarter.
You should use a tool like Spring RESTDocs to generate documentation directly from the code.
The documentation writers can then include this reference information into their documentation and focus on writing the copy to introduce it and provide context and use cases.
They can focus on the story around it because they've recaptured the time they were losing itemizing all the methods and parameters.

You should look for a similar type of solution for creating other types of reference documentation, such as a table of configuration properties or environment variables.
Software developers should be mindful of giving the documentation team a lot of work that could be offloaded to a tool.

// SAW: Alternatives: N·W·I (Never Write It); J·G·I (Just Generate It) aka like Just Do It; A·G·I (Always Generate It)
(slide concept: N·D·I)
The message to communicate to writers is this:
Why write what the computer can generate for you?
This goes even further than DRY.
It's NDI.
Never Do It.

The nature of software development has changed, and so must the documentation tools.
If the docs team expects to keep up with software development, they too must adopt these DRY and NDI practices.
