== Writers are Swamped

The nature of software development has changed.
Specifically, the pace of development has increased.
The impact of this change can be observed through the workload of documentation teams.
Talk to any documentation team and I guarantee you they'll say they're behind, buried in work, just barely holding on, or have no time for new initiatives.

In all likelyhood, they probably are doing too much.
Or, perhaps I should say not enough of the right thing.
We need to look for ways to get them out of having to do rote tasks and let them instead focus on the writing.
Software developers in particular should be mindful of giving the documentation team a lot of work that could be offloaded to a tool.

What's one of the main techniques we use in development to reduce the surface area of what we have to maintain?

(interaction)

Look, we're already violating the rule. DRY: Don't Repeat Yourself.

If there are two places in the documentation that have the same content, whether it's the introduction to a tutorial or a reference table, that information should be centralized.
This can be done by moving the content into a shared partial and including it wherever it's needed.

I knew one documentation team that spent a substantial amount of time updating version numbers when a new version was released or a product was renamed.
This could be avoided by using variables for version numbers and product names (which we call attributes in AsciiDoc).

You can combine the last two techniques and have shared templates that have placeholders that are populated using templates.
The Spring team does this for the parts of their quickstart guides that are shared between projects.

I also knew a documentation team that would hand create release notes files for every release of every product, for which there were many.
Why would a writer be recreating release notes files.
Surely these can be generated and published somewhere by the software release process.
If you see your documentation team doing this, do something about it.
If they really want it to be part of the docs, publish it into a format that their documentation tool can consume (JSON, AsciiDoc, HTML, etc).

Another big time waster are reference tables.
There is absolutely no reason to be hand editing them.
First of all, it's extremely error prone and hard to keep in sync.
Secondly, it's tedious and boring.
Again, look for this happening and put an end to it.

If you are creating a REST API which, of course, needs to be documented, then you should be using a tool like Spring RESTDocs to generate documentation directly from the code.
The documentation writers can then include this reference information into their documentation and write copy around it.
But at least they don't have to be itemizing all of the methods and parameters!

You should look for a simliar type of solution for creating other types of reference documentation, such as a table of configuration properties or environment variables.
Keep it DRY!

If there is sample output in the documentation, that should be generated as well.
And, as we already talked about (will talk about?), the examples themselves should be included from a test suite (ideally) or shared project.

Another way to accelerate writers is to give them templates to create new documents, sections, or a whole folder structure.
Just think about how you develop.
Chances are, you use some sort of wizard to get started on a task, whether it's to create a new project or just a Java class.
Why do we expect writers to start from a blank page?
If we can give them tools to create new things, even if it's a small thing, it will likely have a big impact on motivation and givem them momentum.

Finally, and a big one, with documentation teams so busy all the time, how do they even know what to update?
As developers, we are pretty much driven by notifications.
We get a notification that something happened, something new is available, and we give that thing attention.
Writers can't possibly scan all the hundreds or thousands of documents they have to maintain.
They need some pointers.
They should be able to receive notifications about the sofware that the content documents so they have a burndown list of what to evaluate.
If any part of that notification can trigger an automatic update, such as updating a version number, then that should definitely be done to save them the trouble.
One tool that comes to mind is greenkeeper or dependencies.io.
These tools send automatic pull requests to update the dependencies of a project when new versions become available.
(screenshot: https://github.com/parse-community/parse-server/pull/4227)
This is definitely something that could be developed for documentation as well.
Just think of all the time it would save.

The nature of software development has changed, and so must the documentation tools.
If the docs team expects to keep up with software development, they too must adopt DRY practices.
