= Publishing is Strenuous

// .challenge; Image
Slide: Man free climbing on mountain slope

Once you make a change, you know people are going to ask, "`When will published?`"
Heck, you want to get it published too.
But right now, this is an extremely painful process for writers.
You see, the writing part is natural for them.
It's what they do.
But then there's this huge barrier they need to scale in order to get their words to a place people can read them.
They find themselves quickly in over their heads because it's not a rock face they know how to free climb.

Just think about a project you've worked on that required a manual release.
The first thing you have to do is remember what steps are even necessary.
If it's been awhile, it kind of feels like your starting over from the beginning.
And that can be very painful.

It shouldn't be.
Every step between making a change and publishing should be automated.

// .solution; Typography
Slide: Continuous delivery

In engineering, we recognize this as the practice of continuous delivery.
In writing, we call it "`push to publish`".

A writer makes a change and submits a pull request.
The reviewer approves that change and merges it to master.
From there, it goes straight to production (barring any gateway criteria).

There's a lot more to gain from continuous delivery--push to publish--than speed and productivity.
A CD process eradicates manual steps.
And trust me, this is a place where manual steps love to fester.
We worked with one client who required a person to manually run the build, then manually copy all the files to a CMS using a web interface, then manually press the publish button.
That's ludicrous.

// Solution support; like travis deployment config
Slide: _Something to show or represent the automated build_

What you want is to be able to describe the entire publishing process in a script (better yet, a configuration file) so you can run it exactly the same every time any time you want.
That implies the documentation has a build.
But it's even more than that.
It means that all the configuration for the documentation site is stored with the build, which is the practice of configuration as code.
The immediate benefit of CD is that it's makes the entire process self-documenting.
You don't have the find the person with the specialized knowledge about how the documentation site is published.
It should all be right there in the job definition.

// Solution support
Slide: _Something to show or represent the CI job configuration - possibly a travis.yml file_

So the build is a prerequisite for achieving push to publish.
It also prevents drift between different environments.
We worked with another client who had a build, but the script lived exclusively in each CI job configuration.
That means no two CI jobs worked exactly the same way and there was no transparency.
I know, the horror.
I honestly feel sorry for the person who had to maintain them, except I really don't.
And let me just tell you, a script that only lives in Jenkins is not a script that is tested.
That story doesn't end well.

////
SAW: These 3 sentences don't really add anything to this discussion.

Some teams may buy into this automation process, but be wary of the delivery part.
Of course, you can add a gateway criteria for controlled releases.
But the point is, that step should be as simple as pressing a button.
////

As soon as a step is introduced that only one person knows how to perform, or it's documented in a wiki page somewhere, you're free climbing again.

// Solution support
Slide: _Something to show or represent the webhook_

We've talked about the publish part, but what about the push part.
What triggers this process.
That's another important aspect of CD.
There should be a process that watches for changes.
When a change is detected, perhaps on a qualified branch like the master branch or an active version branch, it should trigger the CD pipeline.
The secret here are webhooks.
A webhook essentially allows another application to subscribe to events that occur on GitHub.
For example, you can have a webhook fire when code is pushed to the repository.
The webhook will then send a ping to that application to let it know something interesting happened.
The receiver of that webhook can be the CI server, which can target and trigger a specific job.

// .takeaway; probably Typography
Slide: Publishing should never be manual. Set up a push to publish CD pipeline for your docs.

Publishing should never be a manual process.
It's very hard on the writer and it leads to inconsistencies.
The bottom line is, if you want to make documentation less strenuous, the best thing you can do is set up CD, or push to publish.
With push to publish in place, the writer can just walk right across the border between development and production.
No barriers to scale.

Once the production pipeline is set up with push to publish, the next logical step is automation for staging environments and the local environment.

// Note for me: Go to Cannot preview next
